### ISSUE TITLE
Time shows 30 minutes delay than actual time

### ISSUE THREAD

**Issue by NiharKashyap** [iamshaunjp/flutter-beginners-tutorial#20]
I followed your YouTube tutorial to make this project. However when I chose the time of India it showed me the time 30 minutes behind the actual time. e.g. If it is 12:30 the clock shows 12. The World Time api gives the time correctly but this line : `DateTime now = DateTime.parse(datetime);` gives the wrong time output. Is it a problem with the DateTime module or my OS timezone?
My time zone url is `'Asia/Kolkata'`

**Comment by YuneshShrestha** [comment]
Actually we just added hour and left minutes in our datetime by using substring.

So you can try this.

 String offsethour = data['utc_offset'].substring(1,3);
 String offsetminutes = data['utc_offset'].substring(4,6);
 DateTime now = DateTime.parse(geotime);
  now = now.add(Duration(hours: int.parse(offsethour))); 
  now = now.add(Duration(minutes: int.parse(offsetminutes))); 
  time = DateFormat.jm().format(now);

**Comment by YuneshShrestha** [comment]
> I followed your YouTube tutorial to make this project. However when I chose the time of India it showed me the time 30 minutes behind the actual time. e.g. If it is 12:30 the clock shows 12. The World Time api gives the time correctly but this line : `DateTime now = DateTime.parse(datetime);` gives the wrong time output. Is it a problem with the DateTime module or my OS timezone?
> My time zone url is `'Asia/Kolkata'`

---------------------------------------------------------------------------------------------------------------------------------------
Actually we just added hour and left minutes in our datetime by using substring.

So you can try this.

String offsethour = data['utc_offset'].substring(1,3);
String offsetminutes = data['utc_offset'].substring(4,6);
DateTime now = DateTime.parse(geotime);
now = now.add(Duration(hours: int.parse(offsethour)));
now = now.add(Duration(minutes: int.parse(offsetminutes)));
time = DateFormat.jm().format(now);

**Comment by NiharKashyap** [comment]
Thanks. It works fine now
