### ISSUE TITLE
NULL is not subtype of type 'Map<dynamic, dynamic> in type cast   (Lesson #30)

### ISSUE THREAD

**Issue by Kweldop** [iamshaunjp/flutter-beginners-tutorial#63]
======== Exception caught by widgets library =======================================================
The following _CastError was thrown building Home(dirty, dependencies: [_ModalScopeStatus], state: _HomeState#30fff):
type 'Null' is not a subtype of type 'Map<dynamic, dynamic>' in type cast

The relevant error-causing widget was: 
  Home Home:file:///D:/world-clock/worldclock/lib/main.dart:12:29
When the exception was thrown, this was the stack: 
#0      _HomeState.build (package:worldclock/pages/home.dart:18:59)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4992:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878:15)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859:5)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5041:11)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
...     Normal element mounting (275 frames)
#282    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#283    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#284    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447:32)
...     Normal element mounting (416 frames)
#700    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#701    Element.updateChild (package:flutter/src/widgets/framework.dart:3592:18)
#702    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1195:16)
#703    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1164:5)
#704    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1111:18)
#705    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2605:19)
#706    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1110:13)
#707    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:945:7)
#708    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:925:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
====================================================================================================

======== Exception caught by widgets library =======================================================
The following _CastError was thrown building Home(dirty, dependencies: [_ModalScopeStatus], state: _HomeState#30fff):
type 'Null' is not a subtype of type 'Map<dynamic, dynamic>' in type cast

The relevant error-causing widget was: 
  Home Home:file:///D:/world-clock/worldclock/lib/main.dart:12:29
When the exception was thrown, this was the stack: 
#0      _HomeState.build (package:worldclock/pages/home.dart:18:59)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4992:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878:15)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#5      StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#7      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#11     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#18     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#19     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#20     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#27     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#33     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#38     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#39     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#40     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#44     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#47     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#49     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#53     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#56     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#57     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#58     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#60     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#63     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#64     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#65     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#67     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#71     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#73     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#76     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#77     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#78     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#80     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#82     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#85     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#86     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#87     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#88     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#91     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#92     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#94     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#95     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#96     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#97     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#100    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#103    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#104    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#105    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#106    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#107    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#109    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#110    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#112    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#113    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#114    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#115    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#116    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#119    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#120    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#121    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#124    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#125    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#126    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#128    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#129    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#130    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#132    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#133    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#134    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#135    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#136    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#137    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#138    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#141    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#142    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#143    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#144    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#146    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#147    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#148    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#149    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#151    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#152    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#153    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#154    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#155    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#156    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#157    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#158    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#159    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#160    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#161    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#162    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#163    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#164    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#165    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#166    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#167    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#168    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#169    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#170    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#171    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#172    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:881:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)

**Comment by Bioust** [comment]
try this
data = ModalRoute.of(context)!.settings.arguments as Map <dynamic, dynamic>;
